apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  serviceName: "minio"
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          command: ["/bin/sh", "-c"]
          args:
            - minio server /data --console-address :9090
          ports:
            - containerPort: 9090
            - containerPort: 9000
          volumeMounts:
            - mountPath: "/data"
              name: data
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - port: 9090
      targetPort: 9090
      name: console
    - port: 9000
      targetPort: 9000
      name: s3
  type: NodePort
