apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  volumeName: minio-pv
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi 
  accessModes:
    - ReadWriteOnce 